export const skillsData = [
    "C++",
    "Golang",
    "Java",
    "Python",
    "C",
    "C#",
    "MIPS Assembly Language",
    "HTML",
    "CSS",
    "Javascript",
    "Docker",
    "Kubernetes",
    "Tailwind",
    "React",
    "Git",
    "Unreal Engine",
    "Unity Engine",
    "MATLAB",
    "Matplotlib",
    "Numpy",
    "Jupyter Notebook",
    "Visual Studio",
    "Valgrind",
];
