export const skillsData = [
    "C++",
    "Python",
    "C",
    "C#",
    "MIPS Assembly Language",
    "HTML",
    "CSS",
    "Tailwind",
    "React",
    "Git",
    "Unreal Engine",
    "Unity Engine",
    "MATLAB",
    "Matplotlib",
    "Numpy",
    "Jupyter Notebook",
    "Visual Studio",
    "Valgrind",
];
